version: '3.5'

volumes:
  db:
    driver: local

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/swfy
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/data/swfy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_HOST}"]
      interval: 30s
      retries: 3
      timeout: 10s